const images = [
  { id: "1", imageName: "../../17kv/01.jpg", tag: "кухня" },
  { id: "2", imageName: "../../17kv/02.jpg", tag: "кухня" },
  { id: "3", imageName: "../../17kv/03.jpg", tag: "кухня" },
  { id: "4", imageName: "../../17kv/04.jpg", tag: "кухня" },
  { id: "5", imageName: "../../17kv/05.jpg", tag: "гостиная" },
  { id: "6", imageName: "../../17kv/06.jpg", tag: "гостиная" },
  { id: "7", imageName: "../../17kv/07.jpg", tag: "гостиная" },
  { id: "8", imageName: "../../17kv/08.jpg", tag: "гостиная" },
  { id: "9", imageName: "../../17kv/012.jpg", tag: "спальня" },
  { id: "10", imageName: "../../17kv/013.jpg", tag: "спальня" },
  { id: "11", imageName: "../../17kv/014.jpg", tag: "спальня" },
  { id: "12", imageName: "../../17kv/015.jpg", tag: "спальня" },
  { id: "13", imageName: "../../17kv/018.1.jpg", tag: "детская" },
  { id: "14", imageName: "../../17kv/019.1.jpg", tag: "детская" },
  { id: "15", imageName: "../../17kv/020.1.jpg", tag: "детская" },
  { id: "16", imageName: "../../17kv/021.1.jpg", tag: "детская" },
  { id: "13", imageName: "../../17kv/022.jpg", tag: "кабинет" },
  { id: "14", imageName: "../../17kv/023.jpg", tag: "кабинет" },
  { id: "15", imageName: "../../17kv/024.jpg", tag: "кабинет" },
  { id: "16", imageName: "../../17kv/025.jpg", tag: "кабинет" },
  { id: "13", imageName: "../../17kv/029.jpg", tag: "ванная" },
  { id: "14", imageName: "../../17kv/030.jpg", tag: "ванная" },
  { id: "15", imageName: "../../17kv/031.jpg", tag: "ванная" },
  { id: "16", imageName: "../../17kv/032.jpg", tag: "ванная" },
  { id: "13", imageName: "../../17kv/026.1.jpg", tag: "гардеробная" },
  { id: "14", imageName: "../../17kv/027.1.jpg", tag: "гардеробная" },
  { id: "15", imageName: "../../17kv/028.2.jpg", tag: "гардеробная" },
  { id: "16", imageName: "../../17kv/09.jpg", tag: "прихожая" },
  { id: "16", imageName: "../../17kv/010.jpg", tag: "прихожая" },
  { id: "16", imageName: "../../17kv/011.jpg", tag: "прихожая" },
];

export default images;
